### ISSUE TITLE
Hi.

### ISSUE THREAD

**Issue by LordBSD** [shufean/BlackJack21-Multiplayer-Client-Server-Application#1]
I am not a programmer but I have common sense, and I use linux, BSD and can compile things and stuff and I am good at getting things working. I edited the database file and gave it my user pass, i installed eclipse, and got this all mostly working but I know nothing of java. I am getting this after i start mirror one, mirror two, the client and then click "start" on the main gui. I tried both with and without an empty password, of course changing my mysql server to reflect those changes.
 
`
no
no
Cannot connect to database com.blackjack.server
java.sql.SQLException: java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Long
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1078)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:989)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:975)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:920)
	at com.mysql.jdbc.ConnectionImpl.buildCollationMapping(ConnectionImpl.java:1074)
	at com.mysql.jdbc.ConnectionImpl.initializePropsFromServer(ConnectionImpl.java:3590)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2531)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2301)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:834)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:416)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:317)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.blackjack.server.DatabaseConnection.connect(DatabaseConnection.java:159)
	at com.blackjack.server.DatabaseConnection.setIntoUserTable(DatabaseConnection.java:8)
	at com.blackjack.server.BlackJackServer.writeClientlist(BlackJackServer.java:284)
	at com.blackjack.server.ServerSocketConnection.connect(ServerSocketConnection.java:61)
	at com.blackjack.server.BlackJackServer.createConnections(BlackJackServer.java:241)
	at com.blackjack.server.BlackJackServer.<init>(BlackJackServer.java:64)
	at com.blackjack.server.MirrorServerOne.<init>(MirrorServerOne.java:17)
	at com.blackjack.server.MirrorServerOne.main(MirrorServerOne.java:22)
Caused by: java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Long
	at com.mysql.jdbc.ConnectionImpl.buildCollationMapping(ConnectionImpl.java:1019)
	... 22 more
Exception in thread "main" java.lang.NullPointerException
	at com.blackjack.server.DatabaseConnection.setIntoUserTable(DatabaseConnection.java:11)
	at com.blackjack.server.BlackJackServer.writeClientlist(BlackJackServer.java:284)
	at com.blackjack.server.ServerSocketConnection.connect(ServerSocketConnection.java:61)
	at com.blackjack.server.BlackJackServer.createConnections(BlackJackServer.java:241)
	at com.blackjack.server.BlackJackServer.<init>(BlackJackServer.java:64)
	at com.blackjack.server.MirrorServerOne.<init>(MirrorServerOne.java:17)
	at com.blackjack.server.MirrorServerOne.main(MirrorServerOne.java:22)`

Please assist I want to play this with my wife it looks great. Thank you for your work.

**Comment by shufean** [comment]
Glad to know about your interest on this project. I would be very happy to help on the code, though its been a while I've updated it. 

From the error messages it looks like you're having some issue with the DatabaseConnection class. Make sure you provided all the database credentials (userName, password, url, port, and driver) correct. And if you look closely at line 156: String url = "jdbc:mysql://localhost:3306/**blackjack**"; you will notice the database name "blackjack" which is very easy to miss. If you try updating your code according to your database, it should work. 

Let me know if there is any progress.

Thanks

**Comment by LordBSD** [comment]
Hi thanks for the response. I fixed that problem by changing and using the latest mysql jdbc connector. It worked great. I worked on this for several hours today and its currently late. I was running into other problems but put it to the side. I dont remember exactly what the problem was and its late here im about to go to sleep, but i will do some more tomorrow and post my results. Thanks for the help I really like this project.

**Comment by LordBSD** [comment]
Ok I made a video in case its something I am doing wrong. It says its processing but it should be ready in a few minutes. https://drive.google.com/open?id=1K_2tqJk0rKlkgBWSOsOR7DHWeG6zcthG Thanks.

**Comment by shufean** [comment]
Nice try.

**Comment by LordBSD** [comment]
So I am doing it right? Do you know what that error could be?

**Comment by shufean** [comment]
OOh, sorry, the video was taking long to load, and I just seen until the error messages. Let me allow some time to try that code in my machine, and i'll update you.

**Comment by LordBSD** [comment]
Ok, Take your time no rush.

**Comment by shufean** [comment]
I've made some update in the project. Here is the summary,

1. Updated two java classes, `client/BlackjackClient.java` and `clientUtilities/ClientProperties.java`, which are responsible for showing the cards properly. Just replace your existing files, no need to update the whole project.
2. Added 5 text files which are necessary for the game play, (`continue.txt, dealer.txt, iplist.txt, trial.txt, turn.txt`). You need to download them and place in your project root directory.

**Two quick hacks,** 
1. `MirrorServerTwo` was created to tackle fault tolerance which you can can skip to play a regular session. Only running `MirrorServerOne` would be sufficient
2.  If server through exception about a user not found, in the `continue.txt `file you can set the value to `no`. Which will prevent the server to to continue the previous game.

One more thing, to avoid data sharing issue, run each client in different machines.

I know, there are lots of room for improvement in this project. Actually it was one of my midterm projects which required some basic features to be implemented.

Let me know if you still have any major issue.

**Comment by LordBSD** [comment]
Thanks for the help. I did what you said on both machines, and clicked refresh on the main project in the eclipse window, although I am not sure that makes a difference besides it showing me the files trial.txt etc. I had to temporarily disable my firewall which is fine, and I see the machine hits it because it says player two connected, but as soon as i connect with the second person I still get this.

`yes
yes
yes
/127.0.0.1 mike
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 0
	at java.util.Vector.get(Unknown Source)
	at com.blackjack.server.ManageSession.<init>(ManageSession.java:57)
	at com.blackjack.server.BlackJackServer.createConnections(BlackJackServer.java:245)
	at com.blackjack.server.BlackJackServer.<init>(BlackJackServer.java:64)
	at com.blackjack.server.MirrorServerOne.<init>(MirrorServerOne.java:17)
	at com.blackjack.server.MirrorServerOne.main(MirrorServerOne.java:22) I hope you are enjoying your weekend.
`

**Comment by shufean** [comment]
Try replacing the content in the newly added .txt files. The error seems like, the content in the text file is out of range.  I just tried the code downloading as it is from github and it worked fine for me, at least I was able to play once.

**Comment by LordBSD** [comment]
ok thanks

**Comment by LordBSD** [comment]
Yeah I screwed something up the first time it works now. Thank you so much. I will follow this project and see if you do anything more with it when you have time. But its perfect as it is. You cant even buy a simple blackjack game like this nowadays without ads or whatnot. certainly not with lan availability so thanks  again.

**Comment by shufean** [comment]
That's awesome and you are most welcome. Hope you'll enjoy it.
